# Generated by Django 4.1.7 on 2023-02-26 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("sale_opportunity", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("hatch", "Hatch"),
                            ("sedan", "Sedan"),
                            ("convertible", "Convertible"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        choices=[(0, "Yellow"), (1, "Blue"), (2, "Gray"), (3, "Other")],
                        default=3,
                    ),
                ),
                ("matricula", models.CharField(max_length=10, unique=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="carfordshop.owner",
                    ),
                ),
            ],
        ),
    ]
